alerta top: ensure text_width is >= 0, otherwise top.py can fail with: (#193)
alertaclient/top.py", line 125, in update
    width=text_width
ValueError: Format specifier missing precision