Bug fix - Using os.uname on Windows
When using python-alerta (api or CLI) from Windows and you don't specify
an origin then a Python Exception is thrown (AttributeError: 'module'
object has no attribute 'uname').
Upon investigation it is the os.uname() (alert.py line 46) call that
cause it as os.uname() is only available on Unix.
(https://docs.python.org/2/library/os.html#os.uname).
Suggestion: use cross-platform 'platform' module instead
(https://docs.python.org/2/library/platform.html#platform.uname)